import codecs

rfd = '/home/meili/Downloads/backup_db2016-12-27.sql'
wfd = '/home/meili/Downloads/backup.sql'

reader = codecs.open(rfd,'r','utf-8')

writer = codecs.open(wfd,'w','utf-8')

for rline in reader:
	try:
		rline.index('CREATE ALGORITHM=UNDEFINED DEFINER=`serapise_serapis`@`localhost`')
		break
	except:
		new_line = rline.replace('date NOT NULL', 'date')
		new_line = new_line.replace('CREATE TABLE ', "SET sql_mode = 'ALLOW_INVALID_DATES'; \n CREATE TABLE ")
		# new_line = new_line.replace('CREATE ALGORITHM=UNDEFINED DEFINER=`serapise_serapis`@`localhost`', 'CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost`")
		new_line = new_line.replace("'0000-00-00'","NULL")
		new_line = new_line.replace("'David Giraldo'","'Meili Vanegas'")
		new_line = new_line.replace("'dgiraldo'","'mvanegas10'")
		writer.write(new_line)

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_antecedentes_familiares` AS select `a`.`id_antecedente_f` AS `id_antecedente_f`,`a`.`id_paciente` AS `id_paciente`,`a`.`fecha_antecedente` AS `fecha_antecedente`,`a`.`hipertension` AS `hipertension`,`a`.`familiar_hipertension` AS `familiar_hipertension`,`a`.`diabetes` AS `diabetes`,`a`.`familiar_diabetes` AS `familiar_diabetes`,`a`.`asma` AS `asma`,`a`.`familiar_asma` AS `familiar_asma`,`a`.`cancer` AS `cancer`,`a`.`familiar_cancer` AS `familiar_cancer`,`a`.`epilepsia` AS `epilepsia`,`a`.`familiar_epilepsia` AS `familiar_epilepsia`,`a`.`transtornos_psico` AS `transtornos_psico`,`a`.`familiar_transtornos` AS `familiar_transtornos`,`a`.`otros` AS `otros`,`a`.`familiar_otros` AS `familiar_otros`,`p1`.`parentesco` AS `f_hiepertension`,`p2`.`parentesco` AS `f_diabetes`,`p3`.`parentesco` AS `f_asma`,`p4`.`parentesco` AS `f_cancer`,`p5`.`parentesco` AS `f_epilepsia`,`p4`.`parentesco` AS `f_transtorno` from ((((((`antecedentes_familiares` `a` left join `parentesco` `p1` on((`a`.`familiar_hipertension` = `p1`.`id_parentesco`))) left join `parentesco` `p2` on((`a`.`familiar_diabetes` = `p2`.`id_parentesco`))) left join `parentesco` `p3` on((`a`.`familiar_asma` = `p3`.`id_parentesco`))) left join `parentesco` `p4` on((`a`.`familiar_cancer` = `p4`.`id_parentesco`))) left join `parentesco` `p5` on((`a`.`familiar_epilepsia` = `p5`.`id_parentesco`))) left join `parentesco` `p6` on((`a`.`familiar_transtornos` = `p6`.`id_parentesco`)));')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_captacion` AS select `captacion`.`id_captacion` AS `id_captacion`,`captacion`.`captacion` AS `captacion`,`captacion`.`orden` AS `orden`,`captacion`.`visible` AS `visible` from `captacion` where (`captacion`.`visible` = 'SI') order by `captacion`.`orden`;')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_citas` AS select `c`.`id_cita` AS `id_cita`,`c`.`fecha_inicio` AS `fecha_inicio`,`c`.`duracion` AS `duracion`,`c`.`fecha_fin` AS `fecha_fin`,`c`.`id_doctor` AS `id_doctor`,`c`.`id_paciente` AS `id_paciente`,`c`.`id_estado` AS `id_estado`,`c`.`observaciones` AS `observaciones`,`c`.`motivo_cancelacion` AS `motivo_cancelacion`,`c`.`responsable_cancelacion` AS `responsable_cancelacion`,`c`.`id_usuario` AS `id_usuario`,`c`.`reprogramada` AS `reprogramada`,`c`.`cant_reprogramada` AS `cant_reprogramada`,`d`.`nombres` AS `nombres`,`d`.`apellidos` AS `apellidos`,`p`.`num_identificacion` AS `num_identificacion`,`p`.`nombre1` AS `nombre1`,`p`.`nombre2` AS `nombre2`,`p`.`apellido1` AS `apellido1`,`p`.`apellido2` AS `apellido2`,concat(`p`.`nombre1`,' ',`p`.`nombre2`,' ',`p`.`apellido1`,' ',`p`.`apellido2`) AS `nombre_completo`,`p`.`telefono` AS `telefono`,`p`.`celular` AS `celular`,`p`.`mail` AS `mail`,`u`.`login` AS `login`,`u`.`nombre` AS `nombre`,`e`.`estado_cita` AS `estado_cita` from ((((`citas` `c` join `doctores` `d`) join `pacientes` `p`) join `usuarios` `u`) join `citas_estado` `e`) where ((`c`.`id_doctor` = `d`.`id_doctor`) and (`c`.`id_paciente` = `p`.`id_paciente`) and (`c`.`id_usuario` = `u`.`id`) and (`c`.`id_estado` = `e`.`id_estado`));')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_consentimiento` AS select `c`.`id_consentimiento` AS `id_consentimiento`,`c`.`fecha` AS `fecha`,`c`.`intervenciones` AS `intervenciones`,`c`.`id_medico` AS `id_medico`,`c`.`id_paciente` AS `id_paciente`,`c`.`tercero` AS `tercero`,`c`.`aprobacion` AS `aprobacion`,`c`.`id_enroll` AS `id_enroll`,concat(`d`.`nombres`,' ',`d`.`apellidos`) AS `doctor`,concat(`p`.`nombre1`,' ',`p`.`nombre2`,' ',`p`.`apellido1`,' ',`p`.`apellido2`) AS `paciente`,`p`.`num_identificacion` AS `num_identificacion` from ((`consentimiento` `c` join `pacientes` `p`) join `doctores` `d`) where ((`c`.`id_paciente` = `p`.`id_paciente`) and (`c`.`id_medico` = `d`.`id_doctor`));')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_detalle_rc` AS select `r`.`id_rc_detalle` AS `id_rc_detalle`,`r`.`id_rc` AS `id_rc`,`r`.`id_producto` AS `id_producto`,`r`.`valor_unidad` AS `valor_unidad`,`r`.`cantidad` AS `cantidad`,`r`.`valor_total` AS `valor_total`,`p`.`descripcion` AS `descripcion`,`p`.`id_tipo_producto` AS `id_tipo_producto`,`tp`.`tipo_producto` AS `tipo_producto`,`rc`.`id_forma_pago` AS `id_forma_pago`,`fp`.`forma_pago` AS `forma_pago`,`rc`.`fecha` AS `fecha` from ((((`recibo_caja_detalles` `r` join `productos` `p`) join `tipo_producto` `tp`) join `recibos_caja` `rc`) join `forma_pago` `fp`) where ((`r`.`id_producto` = `p`.`id_producto`) and (`r`.`id_rc` = `rc`.`id_rc`) and (`rc`.`id_forma_pago` = `fp`.`id_forma_pago`) and (`p`.`id_tipo_producto` = `tp`.`id_tipo_producto`));')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_diagnostico_acupuntura` AS select `dp`.`id_acupuntura_paciente` AS `id_acupuntura_paciente`,`dp`.`fecha` AS `fecha`,`dp`.`id_paciente` AS `id_paciente`,`dp`.`id_acupuntura` AS `id_acupuntura`,`d`.`acupuntura` AS `acupuntura` from (`d_acupuntura_paciente` `dp` join `d_acupuntura` `d`) where (`dp`.`id_acupuntura` = `d`.`id_acupuntura`);')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_diagnostico_cie` AS select `d`.`id_diagnostico` AS `id_diagnostico`,`d`.`fecha` AS `fecha`,`d`.`codigo` AS `codigo`,`d`.`id_paciente` AS `id_paciente`,`d`.`tipo_diagnostico` AS `tipo_diagnostico`,`c`.`descripcion` AS `descripcion` from (`d_descripcion` `d` join `cie` `c`) where (`d`.`codigo` = convert(`c`.`codigo` using utf8));')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_escolaridad` AS select `escolaridad`.`id_escolaridad` AS `id_escolaridad`,`escolaridad`.`escolaridad` AS `escolaridad`,`escolaridad`.`orden` AS `orden`,`escolaridad`.`visible` AS `visible` from `escolaridad` where (`escolaridad`.`visible` = 'SI') order by `escolaridad`.`orden`;')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_estado_civil` AS select `estado_civil`.`id_estado_civil` AS `id_estado_civil`,`estado_civil`.`estado_civil` AS `estado_civil`,`estado_civil`.`orden` AS `orden`,`estado_civil`.`visible` AS `visible` from `estado_civil` where (`estado_civil`.`visible` = 'SI') order by `estado_civil`.`orden`;')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_formula` AS select `f`.`id_formulas` AS `id_formulas`,`f`.`id_paciente` AS `id_paciente`,`f`.`fecha` AS `fecha`,`f`.`responsable` AS `responsable`,`f`.`texto` AS `texto`,`f`.`id_estado` AS `id_estado`,`p`.`num_identificacion` AS `num_identificacion`,`p`.`nombre1` AS `nombre1`,`p`.`nombre2` AS `nombre2`,`p`.`apellido1` AS `apellido1`,`p`.`apellido2` AS `apellido2`,`p`.`telefono` AS `telefono`,`p`.`celular` AS `celular`,`u`.`login` AS `login`,`u`.`nombre` AS `nombre`,`e`.`estado_formula` AS `estado_formula` from (((`formulas` `f` join `pacientes` `p`) join `usuarios` `u`) join `formulas_estado` `e`) where ((`f`.`id_paciente` = `p`.`id_paciente`) and (`f`.`responsable` = `u`.`id`) and (`f`.`id_estado` = `e`.`id_estado`));')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_get_modulos` AS select distinct `m`.`id_modulo` AS `id_modulo`,`m`.`modulo` AS `modulo` from ((`paginasperfil` `vpp` join `paginas` `p`) join `modulos` `m`) where ((`vpp`.`id_pagina` = `p`.`id_pagina`) and (`p`.`id_modulo` = `m`.`id_modulo`) and (`vpp`.`id_perfil` = 1));')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_lista_productos` AS select `p`.`id_producto` AS `id_producto`,concat(`p`.`referencia`,'*',`p`.`descripcion`) AS `producto` from `productos` `p`;')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_medicamentos_formula` AS select `fm`.`id_formula_medicamento` AS `id_formula_medicamento`,`fm`.`id_medicamento` AS `id_medicamento`,`fm`.`id_formula` AS `id_formula`,`fm`.`fasco` AS `fasco`,`fm`.`posologia` AS `posologia`,`fm`.`f_fabricacion` AS `f_fabricacion`,`fm`.`f_vencimiento` AS `f_vencimiento`,`f`.`id_paciente` AS `id_paciente`,`f`.`fecha` AS `fecha`,`m`.`producto` AS `producto`,`m`.`presentacion` AS `presentacion`,`m`.`dosis` AS `dosis` from ((`formula_medicamento` `fm` join `formulas` `f`) join `medicamentos` `m`) where ((`fm`.`id_formula` = `f`.`id_formulas`) and (`fm`.`id_medicamento` = `m`.`id_medicamentos`));')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_nombres_pacientes` AS select `pacientes`.`id_paciente` AS `id_paciente`,`pacientes`.`num_identificacion` AS `num_identificacion`,concat(`pacientes`.`nombre1`,' ',`pacientes`.`nombre2`,' ',`pacientes`.`apellido1`,' ',`pacientes`.`apellido2`) AS `nombres` from `pacientes`;')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_ocupacion` AS select `p`.`id_ocupacion` AS `id_ocupacion`,`p`.`ocupacion` AS `ocupacion`,`p`.`orden` AS `orden`,`p`.`visible` AS `visible` from `ocupacion` `p` where (`p`.`visible` = 'SI') order by `p`.`orden`;')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_ordenes_medicas` AS select `o`.`id_orden` AS `id_orden`,`o`.`id_paciente` AS `id_paciente`,`o`.`responsable` AS `responsable`,`o`.`fecha` AS `fecha`,`o`.`orden` AS `orden`,`p`.`num_identificacion` AS `num_identificacion`,`p`.`nombre1` AS `nombre1`,`p`.`nombre2` AS `nombre2`,`p`.`apellido1` AS `apellido1`,`p`.`apellido2` AS `apellido2`,`p`.`telefono` AS `telefono`,`p`.`celular` AS `celular`,`u`.`login` AS `login`,`u`.`nombre` AS `nombre` from ((`ordenes_medicas` `o` join `pacientes` `p`) join `usuarios` `u`) where ((`o`.`id_paciente` = `p`.`id_paciente`) and (`o`.`responsable` = `u`.`id`));')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_pacientes` AS select `p`.`id_paciente` AS `id`,concat(`p`.`nombre1`,' ',`p`.`nombre2`,' ',`p`.`apellido1`,' ',`p`.`apellido2`) AS `nombre_completo`,`p`.`id_paciente` AS `id_paciente`,`p`.`id_tipo_identificacion` AS `id_tipo_identificacion`,`p`.`num_identificacion` AS `num_identificacion`,`p`.`fecha_nacimiento` AS `fecha_nacimiento`,`p`.`nombre1` AS `nombre1`,`p`.`nombre2` AS `nombre2`,`p`.`apellido1` AS `apellido1`,`p`.`apellido2` AS `apellido2`,`p`.`genero` AS `genero`,`p`.`o_sexual` AS `o_sexual`,`p`.`id_religion` AS `id_religion`,`p`.`id_ocupacion` AS `id_ocupacion`,`p`.`id_profesion` AS `id_profesion`,`p`.`id_escolaridad` AS `id_escolaridad`,`p`.`id_estadocivil` AS `id_estadocivil`,`p`.`natural_de` AS `natural_de`,`p`.`procedente_de` AS `procedente_de`,`p`.`direccion` AS `direccion`,`p`.`telefono` AS `telefono`,`p`.`celular` AS `celular`,`p`.`tel_oficina` AS `tel_oficina`,`p`.`fax` AS `fax`,`p`.`mail` AS `mail`,`p`.`fecha_hora_atencion` AS `fecha_hora_atencion`,`p`.`id_tipo_ss` AS `id_tipo_ss`,`p`.`tipo_ss_2` AS `tipo_ss_2`,`p`.`seguridad_social` AS `seguridad_social`,`p`.`foto` AS `foto`,`p`.`huella` AS `huella`,`p`.`firma` AS `firma`,`p`.`informante` AS `informante`,`p`.`acompanante` AS `acompanante`,`p`.`responsable` AS `responsable`,`p`.`id_parentesco` AS `id_parentesco`,`p`.`tel_responsable` AS `tel_responsable`,`p`.`id_captacion` AS `id_captacion`,`p`.`activo` AS `activo`,`p`.`departamento` AS `departamento`,`p`.`municipio` AS `municipio`,`p`.`rh` AS `rh`,`r`.`religion` AS `religion`,`o`.`ocupacion` AS `ocupacion`,`pro`.`profesion` AS `profesion`,`e`.`escolaridad` AS `escolaridad`,`ec`.`estado_civil` AS `estado_civil`,`t`.`tipo_ss` AS `tipo_ss`,`par`.`parentesco` AS `parentesco`,`cap`.`captacion` AS `captacion`,`ti`.`tipo_identificacion` AS `tipo_identificacion`,`ss`.`seguridad` AS `seguridad`,`d`.`departamento` AS `dpto`,`m`.`municipio` AS `mpio` from ((((((((((((`pacientes` `p` left join `religion` `r` on((`p`.`id_religion` = `r`.`id_religion`))) left join `ocupacion` `o` on((`p`.`id_ocupacion` = `o`.`id_ocupacion`))) left join `profesiones` `pro` on((`p`.`id_profesion` = `pro`.`id_profesion`))) left join `escolaridad` `e` on((`p`.`id_escolaridad` = `e`.`id_escolaridad`))) left join `estado_civil` `ec` on((`p`.`id_estadocivil` = `ec`.`id_estado_civil`))) left join `tipo_ss` `t` on((`p`.`id_tipo_ss` = `t`.`id_tipo_ss`))) left join `parentesco` `par` on((`p`.`id_parentesco` = `par`.`id_parentesco`))) left join `captacion` `cap` on((`p`.`id_captacion` = `cap`.`id_captacion`))) left join `tipo_identificacion` `ti` on((`p`.`id_tipo_identificacion` = `ti`.`id_tipo`))) left join `seguridad_social` `ss` on((`p`.`seguridad_social` = `ss`.`id_seguridad`))) left join `departamentos` `d` on((`p`.`departamento` = `d`.`id_departamento`))) left join `municipios` `m` on((`p`.`municipio` = `m`.`id_municipio`)));')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_pacientes_activos` AS select `view_pacientes`.`id` AS `id`,`view_pacientes`.`nombre_completo` AS `nombre_completo`,`view_pacientes`.`id_paciente` AS `id_paciente`,`view_pacientes`.`id_tipo_identificacion` AS `id_tipo_identificacion`,`view_pacientes`.`num_identificacion` AS `num_identificacion`,`view_pacientes`.`fecha_nacimiento` AS `fecha_nacimiento`,`view_pacientes`.`nombre1` AS `nombre1`,`view_pacientes`.`nombre2` AS `nombre2`,`view_pacientes`.`apellido1` AS `apellido1`,`view_pacientes`.`apellido2` AS `apellido2`,`view_pacientes`.`genero` AS `genero`,`view_pacientes`.`o_sexual` AS `o_sexual`,`view_pacientes`.`id_religion` AS `id_religion`,`view_pacientes`.`id_ocupacion` AS `id_ocupacion`,`view_pacientes`.`id_profesion` AS `id_profesion`,`view_pacientes`.`id_escolaridad` AS `id_escolaridad`,`view_pacientes`.`id_estadocivil` AS `id_estadocivil`,`view_pacientes`.`natural_de` AS `natural_de`,`view_pacientes`.`procedente_de` AS `procedente_de`,`view_pacientes`.`direccion` AS `direccion`,`view_pacientes`.`telefono` AS `telefono`,`view_pacientes`.`celular` AS `celular`,`view_pacientes`.`tel_oficina` AS `tel_oficina`,`view_pacientes`.`fax` AS `fax`,`view_pacientes`.`mail` AS `mail`,`view_pacientes`.`fecha_hora_atencion` AS `fecha_hora_atencion`,`view_pacientes`.`id_tipo_ss` AS `id_tipo_ss`,`view_pacientes`.`tipo_ss_2` AS `tipo_ss_2`,`view_pacientes`.`seguridad_social` AS `seguridad_social`,`view_pacientes`.`foto` AS `foto`,`view_pacientes`.`huella` AS `huella`,`view_pacientes`.`firma` AS `firma`,`view_pacientes`.`informante` AS `informante`,`view_pacientes`.`acompanante` AS `acompanante`,`view_pacientes`.`responsable` AS `responsable`,`view_pacientes`.`id_parentesco` AS `id_parentesco`,`view_pacientes`.`tel_responsable` AS `tel_responsable`,`view_pacientes`.`id_captacion` AS `id_captacion`,`view_pacientes`.`activo` AS `activo`,`view_pacientes`.`departamento` AS `departamento`,`view_pacientes`.`municipio` AS `municipio`,`view_pacientes`.`rh` AS `rh`,`view_pacientes`.`religion` AS `religion`,`view_pacientes`.`ocupacion` AS `ocupacion`,`view_pacientes`.`profesion` AS `profesion`,`view_pacientes`.`escolaridad` AS `escolaridad`,`view_pacientes`.`estado_civil` AS `estado_civil`,`view_pacientes`.`tipo_ss` AS `tipo_ss`,`view_pacientes`.`parentesco` AS `parentesco`,`view_pacientes`.`captacion` AS `captacion`,`view_pacientes`.`tipo_identificacion` AS `tipo_identificacion`,`view_pacientes`.`seguridad` AS `seguridad`,`view_pacientes`.`dpto` AS `dpto`,`view_pacientes`.`mpio` AS `mpio` from `view_pacientes` where (`view_pacientes`.`activo` = 'SI');')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_paginas` AS select `p`.`id_pagina` AS `id_pagina`,`p`.`text` AS `text`,`p`.`url` AS `url`,`p`.`id_modulo` AS `id_modulo`,`m`.`modulo` AS `modulo` from (`paginas` `p` join `modulos` `m`) where (`p`.`id_modulo` = `m`.`id_modulo`);')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_paginas_perfil` AS select `pp`.`id_pagperfil` AS `id_pagperfil`,`pp`.`id_pagina` AS `id_pagina`,`pp`.`id_perfil` AS `id_perfil`,`p`.`perfil` AS `perfil` from (`paginasperfil` `pp` join `perfiles` `p`) where (`pp`.`id_perfil` = `p`.`id_perfil`);')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_parentesco` AS select `p`.`id_parentesco` AS `id_parentesco`,`p`.`parentesco` AS `parentesco`,`p`.`orden` AS `orden`,`p`.`visible` AS `visible` from `parentesco` `p` where (`p`.`visible` = 'SI') order by `p`.`orden`;')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_productos` AS select `p`.`referencia` AS `referencia`,`p`.`descripcion` AS `descripcion`,`p`.`valor_venta` AS `valor_venta`,`p`.`id_tipo_producto` AS `id_tipo_producto`,`p`.`id_producto` AS `id_producto`,`p`.`rips` AS `rips`,`tp`.`tipo_producto` AS `tipo_producto` from (`productos` `p` join `tipo_producto` `tp`) where (`p`.`id_tipo_producto` = `tp`.`id_tipo_producto`);')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_profesiones` AS select `p`.`id_profesion` AS `id_profesion`,`p`.`profesion` AS `profesion`,`p`.`orden` AS `orden`,`p`.`visible` AS `visible` from `profesiones` `p` where (`p`.`visible` = 'SI') order by `p`.`orden`;')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_puntos_paciente` AS select `tp`.`id_t_puntos` AS `id_t_puntos`,`tp`.`id_paciente` AS `id_paciente`,`tp`.`codigo_punto` AS `codigo_punto`,`tp`.`fecha` AS `fecha`,`tp`.`izquierda` AS `izquierda`,`tp`.`derecha` AS `derecha`,`tp`.`lm` AS `lm`,`tp`.`cant_total` AS `cant_total`,`tp`.`acupuntura` AS `acupuntura`,`tp`.`moxibustion` AS `moxibustion`,`tp`.`masaje` AS `masaje`,`tp`.`digitopuntura` AS `digitopuntura`,`tp`.`ventosas` AS `ventosas`,`tp`.`sangria` AS `sangria`,`tp`.`electroacupuntura` AS `electroacupuntura`,`tp`.`ashi` AS `ashi`,`tp`.`auriculopuntura` AS `auriculopuntura`,`tp`.`imanes` AS `imanes`,`tp`.`tonificar` AS `tonificar`,`tp`.`dispersar` AS `dispersar`,`tp`.`regulacion` AS `regulacion`,`p`.`punto` AS `punto`,`p`.`izquierda` AS `p_izquierda`,`p`.`derecha` AS `p_derecha`,`p`.`lm` AS `p_lm` from (`t_puntos` `tp` join `puntos` `p`) where (convert(`tp`.`codigo_punto` using utf8) = `p`.`codigo`);')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_rc` AS select `r`.`id_rc` AS `id_rc`,`r`.`fecha` AS `fecha`,`r`.`id_paciente` AS `id_paciente`,`r`.`elaborador_por` AS `elaborador_por`,`r`.`id_estado` AS `id_estado`,`r`.`observaciones` AS `observaciones`,`r`.`documento` AS `documento`,`r`.`id_forma_pago` AS `id_forma_pago`,`p`.`num_identificacion` AS `num_identificacion`,`p`.`nombre1` AS `nombre1`,`p`.`nombre2` AS `nombre2`,`p`.`apellido1` AS `apellido1`,`p`.`apellido2` AS `apellido2`,`u`.`login` AS `login`,`u`.`nombre` AS `nombre`,`e`.`estado` AS `estado`,`f`.`forma_pago` AS `forma_pago` from ((((`recibos_caja` `r` join `pacientes` `p`) join `usuarios` `u`) join `recibo_caja_estados` `e`) join `forma_pago` `f`) where ((`r`.`id_paciente` = `p`.`id_paciente`) and (`r`.`elaborador_por` = `u`.`id`) and (`r`.`id_estado` = `e`.`id_estado`) and (`r`.`id_forma_pago` = `f`.`id_forma_pago`));')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_religion` AS select `p`.`id_religion` AS `id_religion`,`p`.`religion` AS `religion`,`p`.`orden` AS `orden`,`p`.`visible` AS `visible` from `religion` `p` where (`p`.`visible` = 'SI') order by `p`.`orden`;')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_seguridad_social` AS select `p`.`id_seguridad` AS `id_seguridad`,`p`.`seguridad` AS `seguridad`,`p`.`orden` AS `orden`,`p`.`visible` AS `visible` from `seguridad_social` `p` where (`p`.`visible` = 'SI') order by `p`.`orden`;')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_tipo_identificacion` AS select `p`.`id_tipo` AS `id_tipo`,`p`.`tipo_identificacion` AS `tipo_identificacion`,`p`.`orden` AS `orden`,`p`.`visible` AS `visible`,`p`.`tipo_id` AS `tipo_id` from `tipo_identificacion` `p` where (`p`.`visible` = 'SI') order by `p`.`orden`;')

writer.write('CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_usuarios` AS select `u`.`id` AS `id`,`u`.`login` AS `login`,`u`.`pwd` AS `pwd`,`u`.`nombre` AS `nombre`,`u`.`movil` AS `movil`,`u`.`mail` AS `mail`,`u`.`activo` AS `activo`,`u`.`id_perfil` AS `id_perfil`,`p`.`perfil` AS `perfil` from (`usuarios` `u` join `perfiles` `p`) where (`u`.`id_perfil` = `p`.`id_perfil`);')


reader.close()
writer.close()
